### ISSUE TITLE
Seatower for BG2?

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/BS_Baldurans_Seatower#12]
Would it be possible to port Seatower into BG2? Not saying all of it has to be
ported, but perhaps smaller quests; as inspiration (for the idea) see the other
quest where one has to travel around Amn, and in one place near the coast
there is a seatower (with a demon inside). Perhaps some reduced content
may fit to BG2, so I am not saying to just move all of the area to BG2, just
any smaller part that could fit.

At any rate, that's just an idea.

**Comment by Gitjas** [comment]
No, that doesn't make sense for several reasons.
