### ISSUE TITLE
Tiny Typos #1

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/BS_Baldurans_Seatower#2]
https://github.com/Gibberlings3/BS_Baldurans_Seatower/blob/cb8b4936b1ede895b3aec29fde70e52144fe55e8/bst/dialog/bsdialog.d#L76
Should be `SPPR701` instead of `SPR701`

https://github.com/Gibberlings3/BS_Baldurans_Seatower/blob/cb8b4936b1ede895b3aec29fde70e52144fe55e8/bst/dialog/z_well_encounter.d#L105
Should be `Montaron` instead of `Monatron`

https://github.com/Gibberlings3/BS_Baldurans_Seatower/blob/cb8b4936b1ede895b3aec29fde70e52144fe55e8/bst/dialog/z_roryn_ratquest.d#L324
https://github.com/Gibberlings3/BS_Baldurans_Seatower/blob/cb8b4936b1ede895b3aec29fde70e52144fe55e8/bst/dialog/z_roryn_ratquest.d#L325
Should be `garrick` instead of `garick`

In `YS0119.ARE`:
There is a typo at 0x1b50: should be AMB_S`0`5A instead of AMB_SO5A

**Comment by Gitjas** [comment]
Thanks, fiyed in vEAOB.8.
